# Display
cls  = "00e0"
drw  = "dxyn"

# Subroutines
call = "2nnn"
ret  = "00ee"

# Load
ld1  = "6xkk"
ld2  = "8xy0"
ld3  = "annn"
ld4  = "fx07"
ld5  = "fx0a"
ld6  = "fx15"
ld7  = "fx18"
ld8  = "fx29"
ld9  = "fx33"
ld10 = "fx55"
ld11 = "fx65"

# Arithmetic
## Addition
add1 = "7xkk"
add2 = "8xy4"
add3 = "fx1e"

## Subtraction
sub  = "8xy5"
subn = "8xy7"

# Flow Control

# Jump
jp1  = "1nnn"
jp2  = "bnnn"

## Skip if equal
se1  = "3xkk"
se2  = "5xy0"

## Skip if not equal
sne1 = "4xkk"
sne2 = "9xy0"

## Skip if key
skp  = "ex9e"
sknp = "exa1"

# Bitwise operators

or   = "8xy1"
and  = "8xy2"
xor  = "8xy3"

shr  = "8xy6"
shl  = "8xye"

# Miscellaneous

rnd  = "cxkk"